# Generated by Django 4.2.6 on 2024-06-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ninja',
            new_name='Ninjas',
        ),
    ]
