# Generated by Django 4.2.6 on 2024-06-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_authors_notes_alter_authors_books_alter_books_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='books_authors_app.books'),
        ),
    ]
